In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from matplotlib.pyplot import style
from sklearn import linear_model
import warnings
warnings.filterwarnings(action='ignore', module='scipy', message='^internalgelsd')
pd.options.display.float_format='{:.3f}'.format
%matplotlib inline

In [31]:
data_path = 'file:///C:/Users/JChaotogo/Desktop/New%20folder/nycrimedata.xls'
df = pd.read_excel(data_path)
df.columns = ['city', 'population', 'violentcrime', 'murder', 'raperevised', 'rapelegacy', 'robbery', 'assault', 'propertycrime', 'burglary', 'larceny', 'motortheft', 'arson']

df.head(20)
df.drop(df.index[[0, 1, 2, 3]], inplace=True)
df

,city,population,violentcrime,murder,raperevised,rapelegacy,robbery,assault,propertycrime,burglary,larceny,motortheft,arson
4,Adams Village,1861,0,0,NaN,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,NaN,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,NaN,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,NaN,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,NaN,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,NaN,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,NaN,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,NaN,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,NaN,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,NaN,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,NaN,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,NaN,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,NaN,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,NaN,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,NaN,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,NaN,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,NaN,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,NaN,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,NaN,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,NaN,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,NaN,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,NaN,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,NaN,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,NaN,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,NaN,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,NaN,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,NaN,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,NaN,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,NaN,0,1,3,31,9,20,2,0
33,Brewster,2358,0,0,NaN,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,NaN,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,NaN,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,NaN,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,NaN,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,NaN,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,NaN,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,NaN,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,NaN,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,NaN,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,NaN,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,NaN,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,NaN,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,NaN,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,NaN,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,NaN,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,NaN,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,NaN,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,NaN,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,NaN,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,NaN,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,NaN,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,NaN,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,NaN,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,NaN,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,NaN,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,NaN,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,NaN,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
df.drop(columns='raperevised')

,city,population,violentcrime,murder,rapelegacy,robbery,assault,propertycrime,burglary,larceny,motortheft,arson
4,Adams Village,1861,0,0,0,0,0,12,2,10,0,0
5,Addison Town and Village,2577,3,0,0,0,3,24,3,20,1,0
6,Akron Village,2846,3,0,0,0,3,16,1,15,0,0
7,Albany,97956,791,8,30,227,526,4090,705,3243,142,NaN
8,Albion Village,6388,23,0,3,4,16,223,53,165,5,NaN
9,Alfred Village,4089,5,0,0,3,2,46,10,36,0,NaN
10,Allegany Village,1781,3,0,0,0,3,10,0,10,0,0
11,Amherst Town,118296,107,1,7,31,68,2118,204,1882,32,3
12,Amityville Village,9519,9,0,2,4,3,210,16,188,6,1
13,Amsterdam,18182,30,0,0,12,18,405,99,291,15,0
14,Arcade Village,2053,0,0,0,0,0,39,3,35,1,0
15,Ardsley Village,4523,5,0,0,3,2,33,4,28,1,0
16,Asharoken Village,658,0,0,0,0,0,2,0,2,0,0
17,Attica Village,2522,2,0,0,0,2,5,0,4,1,0
18,Auburn,27270,96,1,20,22,53,859,132,721,6,NaN
19,Avon Village,3333,1,0,0,1,0,25,3,20,2,NaN
20,Baldwinsville Village,7473,5,0,0,1,4,88,10,77,1,0
21,Ballston Spa Village,5418,8,0,0,3,5,94,16,78,0,1
22,Batavia,15374,57,0,7,13,37,559,103,454,2,NaN
23,Bath Village,5733,15,0,1,3,11,191,32,157,2,2
24,Bedford Town,17627,5,0,0,1,4,156,26,127,3,NaN
25,Bethlehem Town,34243,13,0,0,3,10,442,50,388,4,NaN
26,Binghamton,46304,284,3,19,101,161,2349,525,1767,57,NaN
27,Black River,1410,0,0,0,0,0,14,2,12,0,0
28,Blooming Grove Town,12001,8,0,1,0,7,99,20,72,7,NaN
29,Bolivar Village,1022,1,0,0,0,1,4,2,2,0,0
30,Bolton Town,2325,2,0,0,0,2,24,4,20,0,0
31,Boonville Village,2054,1,0,0,0,1,20,6,14,0,0
32,Brant Town,2065,4,0,0,1,3,31,9,20,2,0
33,Brewster,2358,0,0,0,0,0,13,3,10,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,7,27,102,225,2528,449,1997,82,NaN
326,Vestal Town,27980,16,0,2,6,8,571,39,523,9,NaN
327,Walden Village,6887,18,1,2,1,14,142,13,124,5,NaN
328,Wallkill Town,27940,40,0,3,16,21,767,91,650,26,1
329,Walton Village,3012,6,0,1,0,5,68,18,50,0,NaN
330,Warsaw Village,3453,6,0,1,0,5,78,5,73,0,0
331,Washingtonville Village,5828,2,0,0,1,1,58,5,51,2,0
332,Waterford Town and Village,8392,4,0,0,0,4,59,6,52,1,0
333,Waterloo Village,5175,11,0,0,3,8,194,23,169,2,NaN
334,Watertown,28179,109,0,12,16,81,1165,169,953,43,NaN
335,Watervliet,10245,26,1,3,11,11,242,58,163,21,NaN
336,Watkins Glen Village,1862,6,0,0,0,6,92,10,80,2,NaN
337,Waverly Village,4337,5,0,0,1,4,54,9,41,4,NaN
338,Webster Town and Village,43777,21,0,2,3,16,469,101,361,7,NaN
339,Weedsport Village,1797,0,0,0,0,0,25,5,20,0,0
340,Wellsville Village,4574,11,0,1,0,10,164,32,129,3,1
341,Westhampton Beach Village,1732,2,0,0,0,2,44,4,37,3,0
342,West Seneca Town,44821,35,1,1,9,24,896,166,710,20,0
343,Whitehall Village,2604,6,0,0,0,6,62,12,49,1,NaN
344,White Plains,57559,78,1,3,28,46,1232,77,1134,21,NaN
345,Whitesboro Village,3733,4,0,0,0,4,36,14,21,1,0
346,Whitestown Town,9141,0,0,0,0,0,77,13,61,3,0
347,Woodbury Town,10685,3,0,0,2,1,541,9,529,3,NaN
348,Woodridge Village,829,7,0,0,0,7,17,8,9,0,0
349,Woodstock Town,5931,2,0,0,0,2,58,13,45,0,NaN
350,Yonkers,199134,1036,6,25,390,615,2368,470,1662,236,10
351,Yorktown Town,36643,15,0,0,2,13,334,45,287,2,NaN
352,1 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [50]:
#create categorical features for population^2, murder, and robbery
for entry in (df.murder)|(df.robbery):
    if entry>0:
        entry = 1
    else:
        entry = 0
df['murder'] = np.where((df['murder']>0), 1, 0)
df['robbery'] = np.where((df['robbery']>0), 1, 0)
df['populationsquared'] = (df['population']*df['population'])
df

,city,population,violentcrime,murder,raperevised,rapelegacy,robbery,assault,propertycrime,burglary,larceny,motortheft,arson,muder,populationsquared
4,Adams Village,1861,0,0,0,0,0,0,12,2,10,0,0,0,3463321
5,Addison Town and Village,2577,3,0,0,0,0,3,24,3,20,1,0,0,6640929
6,Akron Village,2846,3,0,0,0,0,3,16,1,15,0,0,0,8099716
7,Albany,97956,791,1,0,30,1,526,4090,705,3243,142,NaN,1,9595377936
8,Albion Village,6388,23,0,0,3,1,16,223,53,165,5,NaN,0,40806544
9,Alfred Village,4089,5,0,0,0,1,2,46,10,36,0,NaN,0,16719921
10,Allegany Village,1781,3,0,0,0,0,3,10,0,10,0,0,0,3171961
11,Amherst Town,118296,107,1,0,7,1,68,2118,204,1882,32,3,1,13993943616
12,Amityville Village,9519,9,0,0,2,1,3,210,16,188,6,1,0,90611361
13,Amsterdam,18182,30,0,0,0,1,18,405,99,291,15,0,0,330585124
14,Arcade Village,2053,0,0,0,0,0,0,39,3,35,1,0,0,4214809
15,Ardsley Village,4523,5,0,0,0,1,2,33,4,28,1,0,0,20457529
16,Asharoken Village,658,0,0,0,0,0,0,2,0,2,0,0,0,432964
17,Attica Village,2522,2,0,0,0,0,2,5,0,4,1,0,0,6360484
18,Auburn,27270,96,1,0,20,1,53,859,132,721,6,NaN,1,743652900
19,Avon Village,3333,1,0,0,0,1,0,25,3,20,2,NaN,0,11108889
20,Baldwinsville Village,7473,5,0,0,0,1,4,88,10,77,1,0,0,55845729
21,Ballston Spa Village,5418,8,0,0,0,1,5,94,16,78,0,1,0,29354724
22,Batavia,15374,57,0,0,7,1,37,559,103,454,2,NaN,0,236359876
23,Bath Village,5733,15,0,0,1,1,11,191,32,157,2,2,0,32867289
24,Bedford Town,17627,5,0,0,0,1,4,156,26,127,3,NaN,0,310711129
25,Bethlehem Town,34243,13,0,0,0,1,10,442,50,388,4,NaN,0,1172583049
26,Binghamton,46304,284,1,0,19,1,161,2349,525,1767,57,NaN,1,2144060416
27,Black River,1410,0,0,0,0,0,0,14,2,12,0,0,0,1988100
28,Blooming Grove Town,12001,8,0,0,1,0,7,99,20,72,7,NaN,0,144024001
29,Bolivar Village,1022,1,0,0,0,0,1,4,2,2,0,0,0,1044484
30,Bolton Town,2325,2,0,0,0,0,2,24,4,20,0,0,0,5405625
31,Boonville Village,2054,1,0,0,0,0,1,20,6,14,0,0,0,4218916
32,Brant Town,2065,4,0,0,0,1,3,31,9,20,2,0,0,4264225
33,Brewster,2358,0,0,0,0,0,0,13,3,10,0,0,0,5560164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,Utica,61686,361,1,0,27,1,225,2528,449,1997,82,NaN,1,3805162596
326,Vestal Town,27980,16,0,0,2,1,8,571,39,523,9,NaN,0,782880400
327,Walden Village,6887,18,1,0,2,1,14,142,13,124,5,NaN,1,47430769
328,Wallkill Town,27940,40,0,0,3,1,21,767,91,650,26,1,0,780643600
329,Walton Village,3012,6,0,0,1,0,5,68,18,50,0,NaN,0,9072144
330,Warsaw Village,3453,6,0,0,1,0,5,78,5,73,0,0,0,11923209
331,Washingtonville Village,5828,2,0,0,0,1,1,58,5,51,2,0,0,33965584
332,Waterford Town and Village,8392,4,0,0,0,0,4,59,6,52,1,0,0,70425664
333,Waterloo Village,5175,11,0,0,0,1,8,194,23,169,2,NaN,0,26780625
334,Watertown,28179,109,0,0,12,1,81,1165,169,953,43,NaN,0,794056041
335,Watervliet,10245,26,1,0,3,1,11,242,58,163,21,NaN,1,104960025
336,Watkins Glen Village,1862,6,0,0,0,0,6,92,10,80,2,NaN,0,3467044
337,Waverly Village,4337,5,0,0,0,1,4,54,9,41,4,NaN,0,18809569
338,Webster Town and Village,43777,21,0,0,2,1,16,469,101,361,7,NaN,0,1916425729
339,Weedsport Village,1797,0,0,0,0,0,0,25,5,20,0,0,0,3229209
340,Wellsville Village,4574,11,0,0,1,0,10,164,32,129,3,1,0,20921476
341,Westhampton Beach Village,1732,2,0,0,0,0,2,44,4,37,3,0,0,2999824
342,West Seneca Town,44821,35,1,0,1,1,24,896,166,710,20,0,1,2008922041
343,Whitehall Village,2604,6,0,0,0,0,6,62,12,49,1,NaN,0,6780816
344,White Plains,57559,78,1,0,3,1,46,1232,77,1134,21,NaN,1,3313038481
345,Whitesboro Village,3733,4,0,0,0,0,4,36,14,21,1,0,0,13935289
346,Whitestown Town,9141,0,0,0,0,0,0,77,13,61,3,0,0,83557881
347,Woodbury Town,10685,3,0,0,0,1,1,541,9,529,3,NaN,0,114169225
348,Woodridge Village,829,7,0,0,0,0,7,17,8,9,0,0,0,687241
349,Woodstock Town,5931,2,0,0,0,0,2,58,13,45,0,NaN,0,35176761
350,Yonkers,199134,1036,1,0,25,1,615,2368,470,1662,236,10,1,39654349956
351,Yorktown Town,36643,15,0,0,0,1,13,334,45,287,2,NaN,0,1342709449
352,1 The figures shown in this column for the off...,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
353,2 The figures shown in this column for the off...,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN
354,3 The FBI does not publish arson data unless i...,NaN,NaN,0,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN